version: '3'

services:

### Workspace Utilities Container ###########################

  workspace:
    build:
      context: ./workspace
      args:
        - MAGENTO_ROOT=${MAGENTO_ROOT}
        - CRON=false
        - INSTALL_XDEBUG=false
        - COMPOSER_GLOBAL_INSTALL=false
        - PUID=1000
        - PGID=1000
        - DEBUG=${DEBUG}
    volumes:
      - ${MAGENTO_HOST_SOURCE}:${MAGENTO_ROOT}${APP_CODE_CONTAINER_FLAG}
    tty: true
    environment:
      SSH_AUTH_SOCK: /ssh-agent

  ### PHP-FPM Container #######################################

  php-fpm:
    build:
      context: ./php-fpm
      args:
        - MAGENTO_ROOT=${MAGENTO_ROOT}
        - MAGENTO_RUN_MODE=${MAGENTO_RUN_MODE}
        - INSTALL_XDEBUG=${PHP_ENABLE_XDEBUG}
        - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
        - DEBUG=${DEBUG}
        - VIRTUAL_HOST=${VIRTUAL_HOST}
    volumes:
      - ${MAGENTO_HOST_SOURCE}:${MAGENTO_ROOT}${APP_CODE_CONTAINER_FLAG}
#      - ./logs/xdebug/:/tmp/xdebug
    links:
      - workspace

  ### Nginx Server Container ##################################

  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM=php-fpm
        - PUID=1000
        - PGID=1000
        - DEBUG=${DEBUG}
        - VIRTUAL_HOST=${VIRTUAL_HOST}
        - MAGENTO_ROOT=${MAGENTO_ROOT}
        - MAGENTO_RUN_MODE=${MAGENTO_RUN_MODE}
    volumes:
      - ${MAGENTO_HOST_SOURCE}:${MAGENTO_ROOT}${APP_CODE_CONTAINER_FLAG}
    ports:
      - "80:80"
      - "443:443"

    links:
      - php-fpm

  ### MySQL Container #########################################

  mysql:
    build: ./mysql
    volumes:
      - /Users/shao/.mysql/mysql5.7:/var/lib/mysql:delegated
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  ### Redis Container #########################################

  redis:
    image: redis:3.2-alpine
    volumes:
      - /Users/shao/.redis:/data:delegated
    ports:
      - "6379"
